events {}

http {
  server {
    listen 80;
    server_name _;

    # serve built React files
    location / {
      root /usr/share/nginx/html;
      try_files $uri /index.html;
    }

    # proxy API requests to Node
    location /api/ {
      proxy_pass http://node-server:8081/;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection 'upgrade';
      proxy_set_header Host $host;
      proxy_cache_bypass $http_upgrade;
    }
  }
}
